# **Sprint 9: Creating functions, data structures and loops**

### **Description**

You will solve some everyday life problems by applying data and control structures in Python.

A client of the company you work for asks for a list of very simple programs that would make many processes easier.

You will be asked to program several functions. To submit, you will need to submit both the function code:
```python
def example function(variable1, variable2):
    result = variable1 + variable2    # add the two variables
    return result
```

How to run it to demonstrate that it works correctly, showing the output:

```python
functionexample(3, 8)
```

Try to make all the code you generate as reproducible as possible.

## ⭐ **Level 1** 
#### 1. Body Mass Index calculator
- Write a function that calculates the BMI entered by the user, that is, whoever runs it will have to enter this data. You can get more information about its calculation at: [Body Mass Index What is BMI and how is it calculated](https://muysalud.com/salud/indice-de-masa-corporal-imc-que-es-y-como-se-calcula/).
- The function must classify the result into its respective categories.

*Tip: Try validating the data beforehand, so that it sends a warning message if the data entered by the user is not in the appropriate format or does not take reasonable values.*

In [20]:
def bmi_calculation(weight, height):
    """
    Calculation of BMI using weight (kilograms) and height (meters) using the formula: weight/height²
    """
    return round(weight / pow(height, 2), 2)

def bmi_category(bmi):
    """
    Assigning calculated BMI to its corresponding category
    """
    if bmi > 30:
        category = "Obese"
    elif bmi >= 25: 
        category = "Overweight"
    elif bmi >= 18.5:
        category = "Normal Weight"
    else:
        category = "Underweight"
    
    return category

In [21]:
while True:
    try:
        height = float(input("How tall are you (in meters)?"))

# Anticipating feasible errors for data entry for height
        if (height > 0 and height < 0.5) or height > 3:
            raise ValueError("Error: The height value appears to be an outlier. Consider re-entering it correctly in meters")
        if height <= 0:
            raise ValueError("Error: Height must be greater than zero.")
        else:
             break
        
    except ValueError as e:
            print(e)

while True:
    try:
        weight = float(input("How much do you weigh (in Kg)?"))

# Anticipating feasible errors for data entry for weight
        if (weight > 0 and weight < 15) or weight > 450:
            raise ValueError("Error: The weight value appears to be an outlier. Consider re-entering it correctly in kilograms")
        if weight <= 0:
            raise ValueError("Error: Weight must be greater than zero.")
        else:
             break
        
    except ValueError as e:
            print(e)

bmi_result = bmi_calculation(weight,height)
assigned_cat = bmi_category(bmi_result)

print(f"Your BMI is {bmi_result}, which belongs to the category of {assigned_cat}")

could not convert string to float: 'hi'
could not convert string to float: 'g6h9'
could not convert string to float: '5 0 0'
Error: Height must be greater than zero.
Error: The height value appears to be an outlier. Consider re-entering it correctly in meters
Error: The height value appears to be an outlier. Consider re-entering it correctly in meters
could not convert string to float: 'hi'
could not convert string to float: 'd3g7'
could not convert string to float: '6 4 3'
Error: Weight must be greater than zero.
Error: The weight value appears to be an outlier. Consider re-entering it correctly in kilograms
Error: The weight value appears to be an outlier. Consider re-entering it correctly in kilograms
Your BMI is 21.39, which belongs to the category of Normal Weight

#### 2. Temperature converter
There are several temperature units used in different contexts and regions. The most common are Celsius (°C), Fahrenheit (°F), and Kelvin (K). There are also other units such as Rankine (°Ra) and Réaumur (°Re).

Select at least 2 converters, so that when entering a temperature, it returns at least two conversions, so that they can be saved (remember that a print() can never be saved).

*Tip: Try validating the data beforehand, so that it sends a warning message if the data entered by the user is not in the correct format.*

(EXTRA): Think of a way to store all possible conversions in a single object (List? Dictionary? DataFrame?) instead of writing many if elses based on the source temperature and the destination temperature.

In [38]:
pip install pandas

Requirement already satisfied: pandas in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.22.4 in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asus\appdata\roaming\python\python310\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\asus\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [39]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [40]:
import pandas as pd
df_TempConvertor = pd.read_excel(r"Temperature_Converter.xlsx", index_col = 0)
df_TempConvertor

,CELSIUS,FAHRENHEIT,KELVIN,REAUMUR,RANKINE
CELSIUS,x,(x * 9/5) + 32,x + 273.15,x * 0.8,(x * 9/5) + 491.67
FAHRENHEIT,(x - 32) * 5/9,x,(x - 32) * 5/9 + 273.15,(x - 32) * 4/9,x + 459.67
KELVIN,x - 273.15,(x - 273.15) * 9/5 + 32,x,(x - 273.15) * 0.8,x * 9/5
REAUMUR,x * 1.25,(x * 9/4) + 32,x * 1.25 + 273.15,x,(x * 9/4) + 491.67
RANKINE,(x - 491.67) * 5/9,x - 459.67,x * 5/9,(x - 491.67) * 4/9,x

In [41]:
def TemperatureConvertor(primary, secondary, temperature, df_TempConvertor = df_TempConvertor):

    # Going back to the Excel file to use the proper formula
    formula = df_TempConvertor.loc[primary, secondary]
    result = round(eval(formula, {"__builtins__": {}}, {"x": temperature}), 3)
    
    # Saving the inputs & output
    return {
        "Primary Unit": primary,
        "Primary Temperature": temperature,
        "Secondary Unit": secondary,
        "Secondary Temperature": result
    }

In [42]:
options = {
    1: "Celsius",
    2: "Fahrenheit",
    3: "Kelvin",
    4: "Reaumur",
    5: "Rankine"
}

print("Available options:")
for key, value in options.items():
    print(f"{key}. {value}")

while True:
    try:
        origin_unit = int(input("Enter the corresponding number to the primary unit (1-5): "))
        if origin_unit not in options:
            raise ValueError
        break
    except ValueError:
        print("Please enter an integer between 1 and 5.")

while True:
    try:
        destination_unit = int(input("Enter the corresponding number to the secondary unit (1-5): "))
        if destination_unit not in options:
            raise ValueError
        break
    except ValueError:
        print("Please enter an integer between 1 and 5.")     

origin = options[origin_unit].strip().upper()
destination = options[destination_unit].strip().upper()

while True:
    try:
        temperatureInsertion = float(input("Insert the temperature you would like to convert: "))
        break

    except ValueError as e:
        print(e)

Available options:
1. Celsius
2. Fahrenheit
3. Kelvin
4. Reaumur
5. Rankine
Please enter an integer between 1 and 5.
Please enter an integer between 1 and 5.
Please enter an integer between 1 and 5.

In [43]:
# Getting the user inputs to show the final result
df_input = TemperatureConvertor(origin, destination, temperatureInsertion)

df_output = pd.DataFrame([df_input])
df_output.index = ['']
df_output

 Primary Unit  Primary Temperature Secondary Unit  Secondary Temperature
      REAUMUR                 39.8         KELVIN                  322.9

#### 3. Word counter for a text
Write a function that, given a text, displays the number of times each word appears. Try to handle all possible cases that cause the program not to work correctly.

(EXTRA): What is the average word length of the text you wrote? “Hello, how are you?” should return (4+3+2) / 3 = 3

In [166]:
import re

In [ ]:
def word_count(text):
    """
    Counting words in a sentence, excluding numbers and characters
    """    
    text = text.lower()
    text = re.sub(r"[^\w\s]", " ", text)
    #text = re.findall(r"[a-zA-Z]+", text)
    #words = text.split()
    words = [word for word in text.split() if word.isalpha()]
    count = {}

    for word in words:
        #word = word.strip('.,;:¡!¿?()@$%&~"')
        count[word] = count.get(word, 0) + 1
        
    # Average length
    if not words:
        average = 0.0         
    else:
        length = [len(p) for p in words]
        average = round(sum(length) / len(length), 2)

    return count, average

In [169]:
Sentence = input("Write Your Sentence Here")
print(Sentence)
frequency, avg = word_count(Sentence)
print("Frequency:", frequency)
print("Length Average:", avg)

Hey! ThiS is jUST JusT jUSt a !! 4591 tESt TEst.!? :)
Frequency: {'hey': 1, 'this': 1, 'is': 1, 'just': 3, 'a': 1, 'test': 2}
Length Average: 3.33

#### 4. Reverse dictionary (with possibility of duplicates)
It turns out that the client has a very old survey stored in a dictionary and needs the results in reverse, i.e., by swapping the keys and values. The values ​​and keys in the original dictionary are unique; if this is not the case, the function should print a warning message, along with a list of the values ​​associated with the repeated key.

Look at the following examples to see the expected output.

![alt text](image.png)

In [196]:
def reverse_dictionary(dictionary):
    """
    Creating a new dictionary that converts key to value and value(s) to key from the inserted dictionary
    """
    if not isinstance(dictionary, dict):
        print("Error: Input must be in dictionary format.")

    reversed_dictionary = {}

    for key, value in dictionary.items():
        # If the value already exists in the new dictionary, it is added as a duplicate.
        if value in reversed_dictionary:
            print(f"Warning! The value '{value}' already exists.")
            
            # If there is no list, it is created.
            if not isinstance(reversed_dictionary[value], list):
                reversed_dictionary[value] = [reversed_dictionary[value], key]
            else:
                # In case there is a list, we only add the new key.
                reversed_dictionary[value].append(key)
        else:
            # If the value doesn't exist, it is added.
            reversed_dictionary[value] = key
    
    return reversed_dictionary

In [ ]:
input_dictionary = {'x': 'apple', 'y': 'banana', 'z': 'banana'}

final_reversed_dictionary = reverse_dictionary(input_dictionary)
print(final_reversed_dictionary)

Warning! The value 'banana' already exists.
{'apple': 'x', 'banana': ['y', 'z']}

## ⭐⭐ **Level 2** 
#### 1. Counter and sorter of words in a text
The client was happy with the word counter, but now he wants to read TXT files and calculate the frequency of each word ordered within the usual dictionary entries according to the letter they begin with, that is, the keys must go from A to Z and within A we must go from A to Z. For example, for the file "tu_me_quieres_blanca.txt" the expected output would be:

![alt text](image2.png)

In [199]:
from collections import defaultdict
import string
import pprint

In [204]:
def dictionary_style_word_count(text):
    """
    Creating a dictionary that counts all the words of a text and sorts them alphabetically and frequency-wise
    """

    words = text.lower().split()
    count = defaultdict(int)

    for word in words:
        word_cleaning = word.strip(string.punctuation)
        if word_cleaning:
            count[word_cleaning] += 1

    final_result = {}

    # Extracting the first letter to sort
    for word, freq in count.items():
        letter = word[0]

        if letter not in final_result:
            final_result[letter] = {}

        # Adding the word to the dictionary
        final_result[letter][word] = freq  

    # Sorting the words
    for letter in final_result:
        final_result[letter] = dict(sorted(final_result[letter].items()))

    # Sorting based on the letters
    return dict(sorted(final_result.items()))

In [205]:
with open(r"tu me quieres blanca.txt", encoding="utf-8") as file:
    song = file.read()

pprint.pprint(dictionary_style_word_count(song))

{'a': {'a': 3,
       'agua': 1,
       'al': 2,
       'alba': 4,
       'alcobas': 1,
       'alimenta': 1,
       'alma': 1,
       'amarga': 1,
       'azucena': 1},
 'b': {'baco': 1,
       'banquete': 1,
       'bebe': 1,
       'blanca': 3,
       'boca': 1,
       'bosques': 1,
       'buen': 1},
 'c': {'cabañas': 1,
       'carnes': 2,
       'casta': 3,
       'cerrada': 1,
       'con': 4,
       'conservas': 1,
       'copas': 1,
       'corola': 1,
       'corriste': 1,
       'cuando': 2,
       'cubierto': 1,
       'cuerpo': 1,
       'cuáles': 1},
 'd': {'de': 8, 'dejaste': 1, 'del': 1, 'diga': 1, 'dios': 2, 'duerme': 1},
 'e': {'el': 4,
       'ellas': 1,
       'en': 4,
       'engaño': 1,
       'enredada': 1,
       'entonces': 1,
       'escarcha': 1,
       'espumas': 1,
       'esqueleto': 1,
       'estrago': 1},
 'f': {'festejando': 1, 'filtrado': 1, 'frutos': 1},
 'h': {'habla': 1,
       'hacia': 1,
       'haya': 1,
       'hayas': 1,
       'hermana': 1,
       'hombre': 1,
       'hubiste': 1,
       'huye': 1},
 'i': {'intacto': 1},
 'j': {'jardines': 1},
 'l': {'la': 3,
       'labios': 1,
       'las': 7,
       'lo': 2,
       'los': 4,
       'luna': 1,
       'lévate': 1,
       'límpiate': 1},
 'm': {'mano': 1,
       'manos': 1,
       'margarita': 1,
       'me': 9,
       'mi': 1,
       'mieles': 1,
       'milagros': 1,
       'mojada': 1,
       'montaña': 1,
       'morados': 1},
 'n': {'negros': 1, 'ni': 2, 'no': 1, 'nácar': 1, 'nívea': 2},
 'p': {'perdone': 2,
       'perfume': 1,
       'por': 2,
       'pretendes': 3,
       'preténdeme': 3,
       'puesto': 1,
       'pájaros': 1,
       'pámpanos': 1},
 'q': {'que': 6, 'quedó': 1, 'quieres': 6},
 'r': {'rayo': 1, 'raíz': 1, 'renueva': 1, 'rocas': 1, 'rojo': 1},
 's': {'salitre': 1, 'se': 2, 'sea': 1, 'sean': 1, 'sobre': 2, 'sé': 1},
 't': {'te': 3,
       'tejidos': 1,
       'tenue': 1,
       'tierra': 1,
       'toca': 1,
       'todas': 2,
       'todavía': 1,
       'tornadas': 1,
       'tú': 8},
 'u': {'un': 1, 'una': 1},
 'v': {'vestido': 1, 'vete': 1, 'vive': 1},
 'y': {'y': 5},
 '¡': {'¡me': 1}}

#### 2. Data type conversion
The client receives a list of data and needs to generate two lists, the first where all the elements that could be converted to floats will be and the other where the elements that could not be converted are. Example of the list that the client receives:

![alt text](image3.png)

In [ ]:
def numerically_separator(input_data):
    """
    Separating list elements under the condition of being a number
    """

    convertible = []
    not_convertible = []

    for item in input_data:

        # If it's a list, a tuple, or a set
        if isinstance(item, (list, tuple, set)):
            for subitem in item:
                try:
                    convertible.append(float(subitem))
                except:
                    not_convertible.append(subitem)

        # If it's a single element
        else:
            try:
                convertible.append(float(item))
            except:
                not_convertible.append(item)

    return convertible, not_convertible

In [207]:
# Testing the function
client_list = [ '1.3', 'one' , '1e10' , 'seven', '3-1/2', ('2',1,1.4,'not-a-number'), [1,2,'3','3.4']]

numerics, non_numerics = numerically_separator(client_list)

print(f"Convertible Numbers: {numerics}")
print(f"Simple Elements: {non_numerics}")

Convertible Numbers: [1.3, 10000000000.0, 2.0, 1.0, 1.4, 1.0, 2.0, 3.0, 3.4]
Simple Elements: ['one', 'seven', '3-1/2', 'not-a-number']

## ⭐⭐⭐ **Level 3** 
#### 1. Password generator
Explore the operation of the random module of the numpy library. [Random module in NumPy](https://www.cybrosys.com/blog/random-module-in-numpy)

At this point, the client has detected a problem with the passwords used by their employees. Asdf1234, birthdays or similar. To solve this, they have commissioned us to create a Python function that generates more secure passwords. The function must depend on the following parameters:

- length (int): Password length
- capital letters (bool = True): Whether capital letters should appear
- lowercase (bool = True): Whether lowercase letters should appear
- numbers (bool = True): Whether numbers should appear
- signs (bool = False): If special characters should appear (,-$? or similar)

So, if we execute the function as follows:

```python
create_password(10, True, True, True, True)
```
We should obtain an output (which we must be able to save) like this:

*9Er,5Vn8P$*

Make sure that all criteria are met, and that these passwords are truly random.

(EXTRA) Explore how we could make the function automatically copy the password to the computer's clipboard (as if we had selected it and done ctrl+copy).

In [79]:
import numpy as np
import string
import pyperclip   # To copy to the clipboard

def create_password(length, capital_letters=True, lowercase=True, numbers=True, signs=False):
    """
    Generating a random password with an arbitrary length
    """
    
    chars = ""
    password = []    
    required = sum([capital_letters, lowercase, numbers, signs])
    
    if required == 0:
        raise ValueError("Error: Choose at least one character type.")
    if length < required:
        raise ValueError(f"Error: Password must have at least {required} characters.")

    if capital_letters:
        chars += string.ascii_uppercase
        password.append(np.random.choice(list(string.ascii_uppercase)))

    if lowercase:
        chars += string.ascii_lowercase
        password.append(np.random.choice(list(string.ascii_lowercase)))

    if numbers:
        chars += string.digits
        password.append(np.random.choice(list(string.digits)))

    if signs:
        chars += string.punctuation
        password.append(np.random.choice(list(string.punctuation)))

    # Completing the remaining desired length
    remaining = length - len(password)
    password += list(np.random.choice(list(chars), remaining))

    # Combining all types of characters
    np.random.shuffle(password)

    final_pass = "".join(password)

    pyperclip.copy(final_pass)

    return final_pass

In [80]:
try:
    pswrd = create_password(10, True, True, True, True)

    print(f"Your password is   {pswrd}")
    print("Keep it in a safe place!")
    print("Copied to clipboard!")

except ValueError as e:
    print(e)
    print("Please try again.\n")

Your password is   k7KYb7uS-L
Keep it in a safe place!
Copied to clipboard!

#### 2. Simple data processing
A coworker has asked us for a favor, taking advantage of the fact that she knows we are learning to program. She has a history of Catalan football matches in a file, where she has stored the names of the teams and the results. She needs us to process the data automatically, to extract the results she needs.

Use the file "historic_partits.txt"

You need a program that returns:

- The total number of goals scored by each team.
- The name of the top-scoring team.
- The name of the team with the most goals scored
- The overall standings (each win: 3 pts, draw 1 pts, defeat 0 pts)

For reference, the teams with the most points would be the following:

![alt text](image4.png)

You can use the format that is most convenient for you.

In [10]:
def result_analysis(file_name):
    """
    Analyzing the results in a TXT format to extract the final standing table
    """
    teams = {}

    with open(file_name, "r", encoding="utf-8") as file:
        for line in file:
            try:
                team_A, result, team_B = line.strip().split('\t')   # team_A: home team & team_B: away team
            except ValueError:
                continue
            
            team_A_GF, team_B_GF = map(int, result.split('-'))
            
            # Defining and shaping the final standing table
            for team in [team_A, team_B]:
                teams.setdefault(
                        team,
                        {
                        'MP': 0,
                        'W': 0, 
                        'D': 0, 
                        'L': 0, 
                        'GF': 0, 
                        'GA': 0,
                        'GD': 0, 
                        'Pts': 0
                        }
                    )

            # Counting scored and conceded goals of each team
            teams[team_A]['GF'] += team_A_GF
            teams[team_A]['GA'] += team_B_GF
            teams[team_B]['GF'] += team_B_GF
            teams[team_B]['GA'] += team_A_GF

            # Counting the number of matches played
            teams[team_A]['MP'] += 1
            teams[team_B]['MP'] += 1

            # Counting the points in each match played
            if team_A_GF > team_B_GF:
                teams[team_A]['Pts'] += 3
                teams[team_A]['W'] += 1
                teams[team_B]['L'] += 1
            elif team_A_GF < team_B_GF:
                teams[team_B]['Pts'] += 3
                teams[team_B]['W'] += 1
                teams[team_A]['L'] += 1
            else:
                teams[team_A]['Pts'] += 1
                teams[team_B]['Pts'] += 1
                teams[team_A]['D'] += 1
                teams[team_B]['D'] += 1
                
    for team in teams:
        teams[team]["GD"] = teams[team]["GF"] - teams[team]["GA"]

    return teams

In [ ]:
import pandas as pd

try:
    league_stat = result_analysis("historic partits.txt")
except FileNotFoundError as e:
    print(e)

# Creating a DataFrame to show the final result
final_standing = pd.DataFrame.from_dict(league_stat, orient='index')

league_table = [
    'MP', 
    'W', 
    'D', 
    'L', 
    'GF', 
    'GA',
    'GD',
    'Pts'
]
final_standing = final_standing[league_table]

# Sorting the table based on points, goal difference, and goals scored (descending)
final_standing = final_standing.sort_values(by = ["Pts", "GD", "GF"], ascending = [False, False, False])

most_offensive_team = final_standing['GF'].idxmax()
most_goals_scored = final_standing['GF'].max()
most_defensive_team = final_standing['GA'].idxmax()
most_goals_conceded = final_standing['GA'].max()

print(f"{most_offensive_team} have scored {most_goals_scored} goals, more than any other team!")
print(f"{most_defensive_team} have conceded {most_goals_conceded} goals, more than any other team!")
final_standing

Figueres have scored 161 goals, more than any other team!
Vilafranca have conceded 172 goals, more than any other team!

                     MP   W   D   L   GF   GA  GD  Pts
Girona FC            47  31   3  13  139   94  45   96
Llagostera           56  29   7  20  159  142  17   94
Sabadell             48  26   7  15  141  121  20   85
Cornellà             54  25   7  22  147  146   1   82
RCD Espanyol         55  23  11  21  131  144 -13   80
Figueres             56  23  10  23  161  154   7   79
Lleida Esportiu      52  23   6  23  129  133  -4   75
Terrassa             57  20  14  23  147  164 -17   74
FC Barcelona         44  22   7  15  125  115  10   73
Vilafranca           57  20  12  25  157  172 -15   72
Badalona             48  18  14  16  134  124  10   68
Reus Deportiu        44  20   8  16  119  111   8   68
Nàstic de Tarragona  55  20   8  27  130  148 -18   68
Granollers           49  21   4  24  122  117   5   67
Olot                 54  18  10  26  132  144 -12   64
Sant Andreu          53  17  11  25  123  134 -11   62
Manlleu              43  16   9  18  106  118 -12   57
Prat                 45  16   8  21  106  111  -5   56
Cerdanyola           50  17   5  28  117  133 -16   56
Europa               33  12   5  16   93   93   0   41

In [84]:
final_standing = final_standing.reset_index()
final_standing = final_standing.rename(columns={"index": "Team"})

final_standing = final_standing.reset_index(drop=True)
final_standing.insert(0, "Rank", final_standing.index + 1)

final_standing.index = [""] * len(final_standing)
final_standing

  Rank                 Team  MP   W   D   L   GF   GA  GD  Pts
     1            Girona FC  47  31   3  13  139   94  45   96
     2           Llagostera  56  29   7  20  159  142  17   94
     3             Sabadell  48  26   7  15  141  121  20   85
     4             Cornellà  54  25   7  22  147  146   1   82
     5         RCD Espanyol  55  23  11  21  131  144 -13   80
     6             Figueres  56  23  10  23  161  154   7   79
     7      Lleida Esportiu  52  23   6  23  129  133  -4   75
     8             Terrassa  57  20  14  23  147  164 -17   74
     9         FC Barcelona  44  22   7  15  125  115  10   73
    10           Vilafranca  57  20  12  25  157  172 -15   72
    11             Badalona  48  18  14  16  134  124  10   68
    12        Reus Deportiu  44  20   8  16  119  111   8   68
    13  Nàstic de Tarragona  55  20   8  27  130  148 -18   68
    14           Granollers  49  21   4  24  122  117   5   67
    15                 Olot  54  18  10  26  132  144 -12   64
    16          Sant Andreu  53  17  11  25  123  134 -11   62
    17              Manlleu  43  16   9  18  106  118 -12   57
    18                 Prat  45  16   8  21  106  111  -5   56
    19           Cerdanyola  50  17   5  28  117  133 -16   56
    20               Europa  33  12   5  16   93   93   0   41