# **Sprint 10: Data analytics in Pandas**

### **Description**

In this task you will face a data cleaning and analytics exercise.

We have a dataset from a survey of our workers, and we need to ensure that the data is processed correctly, both in format and readability.

## ⭐ **Level 1** 
#### 1.
- Import the sprint10.xlsx file as a DataFrame. Make sure the file is imported correctly, with the corresponding column names, without manipulating the original file.

- Sort the DataFrame by country of origin. In case of a tie, sort by city name.

- Show the first 10 rows.

Additionally, take a *printout* to verify that the DNI only has unique values.

In [3]:
import pandas as pd
import numpy as np
# !pip install jinja2
from datetime import datetime
import matplotlib.pyplot as plt
import seaborn as sns
from pandas.api.types import (
    is_bool_dtype,
    is_numeric_dtype,
    is_datetime64_any_dtype
)

In [4]:
employee_survey = pd.read_excel("sprint10.xlsx", index_col= 0, skiprows=3)
employee_survey

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional
0,Inês,Ferreira Silva,16928694K,Portugal,Lisboa,25,2,1953,D,1.144 €,NaN,1.0,Grup B
1,Clara,Sánchez Martínez,27724652S,Espanya,Barcelona,18,3,1996,D,1.253 €,1.0,NaN,Grup A
2,Fatima,Fassi,38141675A,Marroc,Rabat,6,11,2005,A,1.441 €,1.0,NaN,Grup A
3,Khadija,Bennani Bennani,59157262R,Marroc,Rabat,20,1,1995,D,1.944 €,NaN,1.0,Grup B
4,Toni,Sánchez García,69630528M,Espanya,Barcelona,9,8,1999,H,1.043 €,NaN,1.0,Grup A
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Marta,Ferrer Ferrer,25161375F,Espanya,Sevilla,1,6,1951,D,1.216 €,NaN,1.0,Grup B
996,Joan,García,52145541P,Espanya,Sevilla,11,4,1959,H,971 €,NaN,1.0,Grup A
997,Laia,Ferrer Martínez,69760120X,Espanya,Barcelona,11,11,1980,D,682 €,NaN,1.0,Grup A
998,Jordi,García,82947791W,Espanya,Barcelona,23,5,1984,H,1.699 €,1.0,NaN,Grup C
999,Clara,Sánchez López,89253307W,Espanya,Bilbao,1,8,1952,D,1.217 €,NaN,1.0,Grup A

In [5]:
# Sorting by country and city
employee_survey = employee_survey.sort_values(by=["País d'origen", "Ciutat"])
employee_survey

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional
21,Mia,Schneider Fischer,28973553Z,Alemanya,Berlín,22,10,1976,A,951 €,NaN,1.0,Grup A
154,Laura,Schneider Fischer,37399141L,Alemanya,Berlín,2,2,1958,D,1.769 €,1.0,NaN,Grup B
224,Lea,Schneider Schneider,37368317L,Alemanya,Berlín,23,10,2005,D,2.013 €,NaN,1.0,Grup B
278,Mia,Fischer,21390098Z,Alemanya,Berlín,11,8,1950,D,1.557 €,1.0,NaN,Grup B
602,Jonas,Schneider,44060014R,Alemanya,Berlín,22,11,1985,H,2.754 €,1.0,NaN,Grup D
...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,Emily,Taylor Jones,89577876S,Regne Unit,Manchester,28,3,1958,D,2.033 €,NaN,1.0,Grup B
728,George,Brown Jones,57441590Y,Regne Unit,Manchester,27,12,1979,H,1.130 €,1.0,NaN,Grup A
751,Olivia,Brown Brown,58204038A,Regne Unit,Manchester,28,8,1952,A,1.023 €,NaN,1.0,Grup A
854,Isla,Jones Brown,28367234K,Regne Unit,Manchester,28,3,1999,D,1.197 €,NaN,1.0,Grup A
872,William,Smith,82046699J,Regne Unit,Manchester,19,5,1997,H,1.405 €,1.0,NaN,Grup A

In [6]:
# Showing the first 10 rows
employee_survey.head(10)

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional
21,Mia,Schneider Fischer,28973553Z,Alemanya,Berlín,22,10,1976,A,951 €,NaN,1.0,Grup A
154,Laura,Schneider Fischer,37399141L,Alemanya,Berlín,2,2,1958,D,1.769 €,1.0,NaN,Grup B
224,Lea,Schneider Schneider,37368317L,Alemanya,Berlín,23,10,2005,D,2.013 €,NaN,1.0,Grup B
278,Mia,Fischer,21390098Z,Alemanya,Berlín,11,8,1950,D,1.557 €,1.0,NaN,Grup B
602,Jonas,Schneider,44060014R,Alemanya,Berlín,22,11,1985,H,2.754 €,1.0,NaN,Grup D
871,Lea,Fischer,14773153R,Alemanya,Berlín,9,9,1986,D,1.370 €,1.0,NaN,Grup A
281,Lea,Müller,23266650S,Alemanya,Hamburg,14,4,2003,D,1.314 €,NaN,1.0,Grup A
435,Anna,Müller,83274277X,Alemanya,Hamburg,1,1,1987,D,2.464 €,NaN,1.0,Grup C
444,Laura,Schmidt Müller,60161784X,Alemanya,Hamburg,15,6,1987,NC,2.035 €,1.0,NaN,Grup C
487,Lukas,Müller Fischer,60982309S,Alemanya,Hamburg,28,3,1971,H,2.042 €,NaN,1.0,Grup B

In [7]:
# verifying that the DNI only has unique values
print(f"Does DNI only have unique values? {employee_survey['DNI'].is_unique}")

Does DNI only have unique values? True

#### 2.
- Create a column that is the full name.

- Create a column if the person was born in Spain or not.

- Put the DNI as the index of the DataFrame (row names).

- Replace the name of the columns Dia de Naixement, Mes de Naixement, and Any de Naixement with Dia, Mes, and Any.

- Replace H with Home, D with Dona, A with Altres and NC with a missing data (nan/null/na).

Show all the changes you've made in a single table.

In [8]:
# Creating a column for full name
employee_survey["Nom Complet"] = employee_survey["Nom"] + " " + employee_survey["Cognoms"]

In [9]:
# Creating a column for whether a person was born in Spain or not
employee_survey["Espanyol/a"] = employee_survey["País d'origen"].apply(lambda x: "Sí" if x == "Espanya" else "No")

In [10]:
# Set DNI as index of the DataFrame
employee_survey.set_index("DNI", inplace=True)

In [11]:
# Renaming birth time data
employee_survey.rename(columns={
                                "Dia de Naixement" : "Dia",
                                "Mes de Naixement" : "Mes",
                                "Any de Naixement" : "Any"
                                }, inplace=True)

In [12]:
# Replacing gender with special letters + specifying missing data

gender_dict = {"H": "Home", 
               "D": "Dona", 
               "A": "Altres", 
               "NC": np.nan}
employee_survey["Gènere"] = employee_survey["Gènere"].replace(gender_dict)
employee_survey

,Nom,Cognoms,País d'origen,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nom Complet,Espanyol/a
DNI,,,,,,,,,,,,,,
28973553Z,Mia,Schneider Fischer,Alemanya,Berlín,22,10,1976,Altres,951 €,NaN,1.0,Grup A,Mia Schneider Fischer,No
37399141L,Laura,Schneider Fischer,Alemanya,Berlín,2,2,1958,Dona,1.769 €,1.0,NaN,Grup B,Laura Schneider Fischer,No
37368317L,Lea,Schneider Schneider,Alemanya,Berlín,23,10,2005,Dona,2.013 €,NaN,1.0,Grup B,Lea Schneider Schneider,No
21390098Z,Mia,Fischer,Alemanya,Berlín,11,8,1950,Dona,1.557 €,1.0,NaN,Grup B,Mia Fischer,No
44060014R,Jonas,Schneider,Alemanya,Berlín,22,11,1985,Home,2.754 €,1.0,NaN,Grup D,Jonas Schneider,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89577876S,Emily,Taylor Jones,Regne Unit,Manchester,28,3,1958,Dona,2.033 €,NaN,1.0,Grup B,Emily Taylor Jones,No
57441590Y,George,Brown Jones,Regne Unit,Manchester,27,12,1979,Home,1.130 €,1.0,NaN,Grup A,George Brown Jones,No
58204038A,Olivia,Brown Brown,Regne Unit,Manchester,28,8,1952,Altres,1.023 €,NaN,1.0,Grup A,Olivia Brown Brown,No
28367234K,Isla,Jones Brown,Regne Unit,Manchester,28,3,1999,Dona,1.197 €,NaN,1.0,Grup A,Isla Jones Brown,No
82046699J,William,Smith,Regne Unit,Manchester,19,5,1997,Home,1.405 €,1.0,NaN,Grup A,William Smith,No

#### 3.
- Merge the Fills and No Fills columns into a single column, using the .apply() method and defining a function that solves the problem. The new column should be called "Fills" and take the values ​​"Sí" or "No".

In [13]:
def column_merger(row):
    '''
    A function to later merge two columns with a new definition
    '''
    if pd.notnull(row['Fills']) and pd.isnull(row['No Fills']):
        return 'Sí'
    elif pd.notnull(row['No Fills']) and pd.isnull(row['Fills']):
        return 'No'
    else:
        return 'Anomaly Detected!'


employee_survey['Fills_merged'] = employee_survey.apply(column_merger, axis=1)

In [14]:
# Deleting the existing column and renaming the new one
employee_survey.drop(columns=["Fills", "No Fills"], inplace=True)
employee_survey.rename(columns={"Fills_merged": "Fills"}, inplace=True)

In [15]:
employee_survey

,Nom,Cognoms,País d'origen,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Grup Professional,Nom Complet,Espanyol/a,Fills
DNI,,,,,,,,,,,,,
28973553Z,Mia,Schneider Fischer,Alemanya,Berlín,22,10,1976,Altres,951 €,Grup A,Mia Schneider Fischer,No,No
37399141L,Laura,Schneider Fischer,Alemanya,Berlín,2,2,1958,Dona,1.769 €,Grup B,Laura Schneider Fischer,No,Sí
37368317L,Lea,Schneider Schneider,Alemanya,Berlín,23,10,2005,Dona,2.013 €,Grup B,Lea Schneider Schneider,No,No
21390098Z,Mia,Fischer,Alemanya,Berlín,11,8,1950,Dona,1.557 €,Grup B,Mia Fischer,No,Sí
44060014R,Jonas,Schneider,Alemanya,Berlín,22,11,1985,Home,2.754 €,Grup D,Jonas Schneider,No,Sí
...,...,...,...,...,...,...,...,...,...,...,...,...,...
89577876S,Emily,Taylor Jones,Regne Unit,Manchester,28,3,1958,Dona,2.033 €,Grup B,Emily Taylor Jones,No,No
57441590Y,George,Brown Jones,Regne Unit,Manchester,27,12,1979,Home,1.130 €,Grup A,George Brown Jones,No,Sí
58204038A,Olivia,Brown Brown,Regne Unit,Manchester,28,8,1952,Altres,1.023 €,Grup A,Olivia Brown Brown,No,No
28367234K,Isla,Jones Brown,Regne Unit,Manchester,28,3,1999,Dona,1.197 €,Grup A,Isla Jones Brown,No,No
82046699J,William,Smith,Regne Unit,Manchester,19,5,1997,Home,1.405 €,Grup A,William Smith,No,Sí

#### 4.
- Create a summary table that allows you to see the average, median, minimum and maximum salary by Gènere.

- Sort the table based on average salary.

In [16]:
# Removing the € sign and the separator point, and converting the result into a number
employee_survey['Salari mensual'] = employee_survey["Salari mensual"].str.replace(" €", "", regex=False).str.replace(".", "", regex=False).astype(float)
employee_survey

,Nom,Cognoms,País d'origen,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Grup Professional,Nom Complet,Espanyol/a,Fills
DNI,,,,,,,,,,,,,
28973553Z,Mia,Schneider Fischer,Alemanya,Berlín,22,10,1976,Altres,951.0,Grup A,Mia Schneider Fischer,No,No
37399141L,Laura,Schneider Fischer,Alemanya,Berlín,2,2,1958,Dona,1769.0,Grup B,Laura Schneider Fischer,No,Sí
37368317L,Lea,Schneider Schneider,Alemanya,Berlín,23,10,2005,Dona,2013.0,Grup B,Lea Schneider Schneider,No,No
21390098Z,Mia,Fischer,Alemanya,Berlín,11,8,1950,Dona,1557.0,Grup B,Mia Fischer,No,Sí
44060014R,Jonas,Schneider,Alemanya,Berlín,22,11,1985,Home,2754.0,Grup D,Jonas Schneider,No,Sí
...,...,...,...,...,...,...,...,...,...,...,...,...,...
89577876S,Emily,Taylor Jones,Regne Unit,Manchester,28,3,1958,Dona,2033.0,Grup B,Emily Taylor Jones,No,No
57441590Y,George,Brown Jones,Regne Unit,Manchester,27,12,1979,Home,1130.0,Grup A,George Brown Jones,No,Sí
58204038A,Olivia,Brown Brown,Regne Unit,Manchester,28,8,1952,Altres,1023.0,Grup A,Olivia Brown Brown,No,No
28367234K,Isla,Jones Brown,Regne Unit,Manchester,28,3,1999,Dona,1197.0,Grup A,Isla Jones Brown,No,No
82046699J,William,Smith,Regne Unit,Manchester,19,5,1997,Home,1405.0,Grup A,William Smith,No,Sí

In [17]:
summary_table = (
    employee_survey.groupby('Gènere')['Salari mensual']
    .agg(['mean', 'median', 'min', 'max'])
    .sort_values('mean')
    .round(2)
)
summary_table

           mean  median    min     max
Gènere
Dona    1469.44  1361.5  665.0  3021.0
Altres  1626.59  1545.0  703.0  3175.0
Home    1643.25  1531.0  737.0  3356.0

#### 5.
- Create a summary table with the average salary by Gènere (rows) and País d'origen (columns).

- Add the averages to the margins of the table.

(EXTRA): Apply conditional formatting to the table to see the highest values ​​in a more intense color

In [18]:
# Creating a summary table as requested
dynamic_table = employee_survey.pivot_table(
    values="Salari mensual", 
    index="Gènere", 
    columns="País d'origen", 
    aggfunc="mean", 
    margins=True
    ).round(2)
dynamic_table

País d'origen,Alemanya,Argentina,Colòmbia,Espanya,França,Itàlia,Marroc,Mèxic,Portugal,Regne Unit,All
Gènere,,,,,,,,,,,
Altres,951.00,1141.00,1030.00,1706.18,NaN,1423.00,1365.00,1372.00,1765.00,1921.00,1626.59
Dona,1804.31,1291.80,1497.75,1460.16,1566.47,1247.18,1405.21,1517.80,1488.55,1489.46,1469.44
Home,2067.43,1583.29,1554.67,1682.11,1389.25,1672.88,1531.00,1625.00,1497.00,1162.56,1643.25
All,1851.38,1463.39,1495.54,1581.21,1462.73,1425.95,1447.33,1558.42,1523.33,1423.56,1560.99

In [19]:
colorful_table = (
    dynamic_table
    .style
    .format('{:.2f}')
    .highlight_max(axis=1, props="color: lightgreen; font-weight: bold;")
)
colorful_table

#### 6.
- Create a new column that is the date of birth in Datetime format from the Dia, Mes, and Any columns. Using this column create a function that, given a date, calculates your current age as of today.

- Use the function you just created to generate a new column in the DataFrame with the current age.

In [20]:
# Creating the birth date column by combining three different columns
employee_survey["Data de Naixement"] = pd.to_datetime(employee_survey[["Dia", "Mes", "Any"]].rename(columns={
    "Dia": "day",
    "Mes": "month",
    "Any": "year"}),
    errors="coerce")

In [21]:
today = datetime.now()
def age_calculator(birth_date):
    age = (today - birth_date).days
    return age // 365

In [22]:
employee_survey['Edat'] = employee_survey['Data de Naixement'].apply(age_calculator)
employee_survey = employee_survey.drop(columns=['Dia', 'Mes', 'Any'])
employee_survey

,Nom,Cognoms,País d'origen,Ciutat,Gènere,Salari mensual,Grup Professional,Nom Complet,Espanyol/a,Fills,Data de Naixement,Edat
DNI,,,,,,,,,,,,
28973553Z,Mia,Schneider Fischer,Alemanya,Berlín,Altres,951.0,Grup A,Mia Schneider Fischer,No,No,1976-10-22,49
37399141L,Laura,Schneider Fischer,Alemanya,Berlín,Dona,1769.0,Grup B,Laura Schneider Fischer,No,Sí,1958-02-02,68
37368317L,Lea,Schneider Schneider,Alemanya,Berlín,Dona,2013.0,Grup B,Lea Schneider Schneider,No,No,2005-10-23,20
21390098Z,Mia,Fischer,Alemanya,Berlín,Dona,1557.0,Grup B,Mia Fischer,No,Sí,1950-08-11,75
44060014R,Jonas,Schneider,Alemanya,Berlín,Home,2754.0,Grup D,Jonas Schneider,No,Sí,1985-11-22,40
...,...,...,...,...,...,...,...,...,...,...,...,...
89577876S,Emily,Taylor Jones,Regne Unit,Manchester,Dona,2033.0,Grup B,Emily Taylor Jones,No,No,1958-03-28,68
57441590Y,George,Brown Jones,Regne Unit,Manchester,Home,1130.0,Grup A,George Brown Jones,No,Sí,1979-12-27,46
58204038A,Olivia,Brown Brown,Regne Unit,Manchester,Altres,1023.0,Grup A,Olivia Brown Brown,No,No,1952-08-28,73
28367234K,Isla,Jones Brown,Regne Unit,Manchester,Dona,1197.0,Grup A,Isla Jones Brown,No,No,1999-03-28,27
82046699J,William,Smith,Regne Unit,Manchester,Home,1405.0,Grup A,William Smith,No,Sí,1997-05-19,29

## ⭐⭐ **Level 2** 
#### 1.
- Using the following DataFrame, append the "Increment" column to the dataframe of the previous level.

```python
df_increment = pd.DataFrame({"Grup":["Grup A","Grup B","Grup C", "Grup D"], 
                             "Increment":["5%","3.5%","2%","8%"]})
```

- Update the salary column based on the percentages attached. Don't manually modify the increments, write Python code to do the necessary conversions.

![alt text](image.png)

In [23]:
# Creating the DataFrame as asked in the question, with a name change to match our main DataFrame
df_increment = pd.DataFrame({"Grup Professional":["Grup A","Grup B","Grup C", "Grup D"], 
                             "Increment":["5%","3.5%","2%","8%"]})

# Data cleaning for further use
df_increment["Increment"] = df_increment["Increment"].str.replace("%", "", regex=False).str.replace(",", ".", regex=False).astype(float) * 0.01
df_increment

  Grup Professional  Increment
0            Grup A      0.050
1            Grup B      0.035
2            Grup C      0.020
3            Grup D      0.080

In [24]:
# Joining two DataFrames while resetting indices to preserve the DNI
employee_survey = pd.merge(employee_survey.reset_index(), df_increment, on="Grup Professional", how="left")

# Updating the salary column by the given percentages
employee_survey["Salari mensual"] = employee_survey["Salari mensual"] * (1 + employee_survey["Increment"])

# Restoring the DNI indices
employee_survey.set_index("DNI", inplace=True)
employee_survey.round(2)

,Nom,Cognoms,País d'origen,Ciutat,Gènere,Salari mensual,Grup Professional,Nom Complet,Espanyol/a,Fills,Data de Naixement,Edat,Increment
DNI,,,,,,,,,,,,,
28973553Z,Mia,Schneider Fischer,Alemanya,Berlín,Altres,998.55,Grup A,Mia Schneider Fischer,No,No,1976-10-22,49,0.05
37399141L,Laura,Schneider Fischer,Alemanya,Berlín,Dona,1830.92,Grup B,Laura Schneider Fischer,No,Sí,1958-02-02,68,0.04
37368317L,Lea,Schneider Schneider,Alemanya,Berlín,Dona,2083.46,Grup B,Lea Schneider Schneider,No,No,2005-10-23,20,0.04
21390098Z,Mia,Fischer,Alemanya,Berlín,Dona,1611.50,Grup B,Mia Fischer,No,Sí,1950-08-11,75,0.04
44060014R,Jonas,Schneider,Alemanya,Berlín,Home,2974.32,Grup D,Jonas Schneider,No,Sí,1985-11-22,40,0.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...
89577876S,Emily,Taylor Jones,Regne Unit,Manchester,Dona,2104.15,Grup B,Emily Taylor Jones,No,No,1958-03-28,68,0.04
57441590Y,George,Brown Jones,Regne Unit,Manchester,Home,1186.50,Grup A,George Brown Jones,No,Sí,1979-12-27,46,0.05
58204038A,Olivia,Brown Brown,Regne Unit,Manchester,Altres,1074.15,Grup A,Olivia Brown Brown,No,No,1952-08-28,73,0.05
28367234K,Isla,Jones Brown,Regne Unit,Manchester,Dona,1256.85,Grup A,Isla Jones Brown,No,No,1999-03-28,27,0.05
82046699J,William,Smith,Regne Unit,Manchester,Home,1475.25,Grup A,William Smith,No,Sí,1997-05-19,29,0.05

#### 2.
Using a loop, export the data for each Professional Group into 4 files (.xlsx or .csv format).

For example: "dades_GrupA.xlsx", "dades_GrupB.xlsx" ...

Export a 5th DataFrame in .xlsx or .csv format that contains how many workers there are for each Professional Group, what their average salary is, and what their median age is.

In [ ]:
for group, group_data in employee_survey.groupby("Grup Professional"):
    
    # Modifying the group name
    group_name = group.replace(" ", "")
    file_name = f"dades_{group_name}.xlsx"
    
    # Export to Excel
    group_data.to_excel(file_name)
    print(f"{file_name} was generated!")


# Creating the 5th DataFrame as requested
df5 = employee_survey.groupby("Grup Professional").agg({
    "Nom": "count",
    "Salari mensual": "mean",
    "Edat": "median"}).round(2)

# Renaming the columns as they were asked for
df5.columns = ["Quantitat de Treballadors", "Sou Mig", "Edat Mediana"]

# Export to Excel as a csv file
df5.to_csv("DataFrame5.csv", index='Grup Professional')

print("\nThe 5th DataFrame has been successfully exported!")
df5

dades_GrupA.xlsx was generated!
dades_GrupB.xlsx was generated!
dades_GrupC.xlsx was generated!
dades_GrupD.xlsx was generated!

The 5th DataFrame has been successfully exported!

                   Quantitat de Treballadors  Sou Mig  Edat Mediana
Grup Professional
Grup A                                   490  1213.32          51.0
Grup B                                   318  1724.55          48.0
Grup C                                   137  2289.19          52.0
Grup D                                    55  3100.82          44.0

## ⭐⭐⭐ **Level 3** 

Level 3 of this sprint is completely different from other sprints you've done so far, as they are more abstract exercises that require a lot of fighting. They don't continue with the same dataset from the previous levels, but rather present you with two new situations that are completely different from each other.

#### 1.

Create a function that takes a dataframe as an input parameter.

The function should automatically create (and export) a chart for each column in the dataframe. For example:

- a histogram/boxplot if the variable is numeric
- some bars of the most frequent values ​​if it is categorical
- some bars of the most frequent years if the data is in date format.

The idea is to create a function that works for **any** dataframe, not just the one we've worked with so far.

Show the result of the function on one of the example datasets contained in the seaborn package. For example, *iris*, *penguins*, or *titanic*.

**Keep in mind that in the next sprint you will work exclusively with graphics. The goal of this exercise is not to create very elaborate graphics, but to solve a need quickly and automatically.**

In [26]:
def chart_plotter(df):
    for col in df.columns:
        series = df[col].dropna()

        plt.figure(figsize=(9,5))

        if is_bool_dtype(series):                            # Boleans
            series.value_counts().plot(kind='bar')
            plt.title(f'The most frequent values of {col}')
            plt.xticks(rotation=45)

        elif is_numeric_dtype(series):                       # Numerics
            sns.histplot(series, kde=True, color='purple')
            plt.title(f'Histogram of {col}')

        elif is_datetime64_any_dtype(series):                # Date & Time
            series.dt.year.value_counts().sort_index().plot(kind='bar', color='orange', edgecolor='red')
            plt.title(f'The most frequent years in {col}')

        else:                                                # None of the above
            series.value_counts().head(10).plot(kind='bar', color='#DAF7A6', edgecolor='#BB8FCE')
            plt.title(f'The most frequent values of {col}')
            plt.xticks(rotation=45)

        plt.tight_layout()
        file_name = f"{col}_chart.png"
        plt.savefig(file_name)
        plt.close()
        print(f"{file_name} exported successfully!")

In [27]:
iris = sns.load_dataset("iris")
chart_plotter(iris)

sepal_length_chart.png exported successfully!
sepal_width_chart.png exported successfully!
petal_length_chart.png exported successfully!
petal_width_chart.png exported successfully!
species_chart.png exported successfully!

In [28]:
penguins = sns.load_dataset("penguins")
chart_plotter(penguins)

species_chart.png exported successfully!
island_chart.png exported successfully!
bill_length_mm_chart.png exported successfully!
bill_depth_mm_chart.png exported successfully!
flipper_length_mm_chart.png exported successfully!
body_mass_g_chart.png exported successfully!
sex_chart.png exported successfully!

In [29]:
titanic = sns.load_dataset("titanic")
chart_plotter(titanic)

survived_chart.png exported successfully!
pclass_chart.png exported successfully!
sex_chart.png exported successfully!
age_chart.png exported successfully!
sibsp_chart.png exported successfully!
parch_chart.png exported successfully!
fare_chart.png exported successfully!
embarked_chart.png exported successfully!
class_chart.png exported successfully!
who_chart.png exported successfully!
adult_male_chart.png exported successfully!
deck_chart.png exported successfully!
embark_town_chart.png exported successfully!
alive_chart.png exported successfully!
alone_chart.png exported successfully!

#### 2.
Load the file matriu_distancies.xlsx into pandas, so that the row names and column names are those of the cities. Delete "Las Palmas de Gran Canaria" and "Palma" so that we can make the trip by car.

Source: [Best Routes](https://espana.mejoresrutas.com/tabla-de-distancias/es/)

We are interested in visiting all the main cities in Spain while traveling the shortest possible distance.

**You don't have to do it optimally, we are interested in you developing a reasonable solution using the tools you currently have.**

For example, a simple (but not optimal) approach would be to always go to the nearest city that we haven't visited yet.

Write a function that, given a distance matrix and the origin city, returns a route of minimum length, with the order of visits. Also, gives the total distance traveled. 

(EXTRA) From which city would the route be shortest with the proposed algorithm?

In [30]:
# Reading the Excel file
df_distance = pd.read_excel("matriu_distancies.xlsx", index_col=0)

# Removing the desired cities
outlier_cities = ["Las Palmas de Gran Canaria", "Palma"]
df_distance_pruned = df_distance.drop(columns = outlier_cities, index = outlier_cities, errors = "ignore")

# Changing self-distance to 0
df_distance_pruned = df_distance_pruned.fillna(0)
df_distance_pruned

,Barcelona,Valencia,Sevilla,Zaragoza,Málaga,Murcia,Bilbao,Alicante,Córdoba,Valladolid,Vigo,Gijón,Hospitalet de Llobregat
Barcelona,0.0,303.0,831.0,256.0,770.0,471.0,469.0,407.0,711.0,576.0,908.0,686.0,7.0
Valencia,303.0,0.0,541.0,246.0,468.0,177.0,473.0,125.0,421.0,441.0,766.0,632.0,297.0
Sevilla,831.0,541.0,0.0,646.0,158.0,433.0,703.0,495.0,121.0,486.0,588.0,685.0,824.0
Zaragoza,256.0,246.0,646.0,0.0,628.0,408.0,246.0,368.0,535.0,320.0,652.0,444.0,250.0
Málaga,770.0,468.0,158.0,628.0,0.0,323.0,739.0,391.0,133.0,549.0,716.0,766.0,763.0
Murcia,471.0,177.0,433.0,408.0,323.0,0.0,606.0,69.0,320.0,510.0,800.0,726.0,465.0
Bilbao,469.0,473.0,703.0,246.0,739.0,606.0,0.0,583.0,618.0,232.0,486.0,223.0,465.0
Alicante,407.0,125.0,495.0,368.0,391.0,69.0,583.0,0.0,379.0,515.0,821.0,722.0,401.0
Córdoba,711.0,421.0,121.0,535.0,133.0,320.0,618.0,379.0,0.0,419.0,589.0,634.0,704.0
Valladolid,576.0,441.0,486.0,320.0,549.0,510.0,232.0,515.0,419.0,0.0,337.0,224.0,570.0
Vigo,908.0,766.0,588.0,652.0,716.0,800.0,486.0,821.0,589.0,337.0,0.0,289.0,902.0
Gijón,686.0,632.0,685.0,444.0,766.0,726.0,223.0,722.0,634.0,224.0,289.0,0.0,681.0
Hospitalet de Llobregat,7.0,297.0,824.0,250.0,763.0,465.0,465.0,401.0,704.0,570.0,902.0,681.0,0.0

In [31]:
def shortest_path(dist_matrix, home_city):
    """
    Finding a route using the Nearest Neighbor algorithm.
    """

    not_visited = set(dist_matrix.index)

    path = [home_city]
    not_visited.remove(home_city)

    total_distance = 0
    current_city = home_city

    while not_visited:

        # Nearest unvisited city
        next_city = (dist_matrix.loc[current_city, list(not_visited)].idxmin())

        total_distance += dist_matrix.loc[current_city, next_city]

        path.append(next_city)
        not_visited.remove(next_city)
        current_city = next_city

    return path, total_distance

In [ ]:
# Testing the function by a random city
route, distance = shortest_path(df_distance_pruned, "Murcia")

print("Route:")
print(" > ".join(route))

print("\nTotal distance:", distance, "km")

Route:
Murcia > Alicante > Valencia > Zaragoza > Bilbao > Gijón > Valladolid > Vigo > Sevilla > Córdoba > Málaga > Hospitalet de Llobregat > Barcelona

Total distance: 3082.0 km

In [ ]:
# Finding the origin city for the shortest route
distance_order = []

for city in df_distance_pruned.index:

    _, distance = shortest_path(df_distance_pruned, city)

    distance_order.append({"Origin City": city, "Covered Distance (km)": int(distance)})

final_distance_order = (pd.DataFrame(distance_order).sort_values("Covered Distance (km)").reset_index(drop=True))

print(final_distance_order)
print("\n")
print(f"The shortest route is to start from {final_distance_order.loc[0, 'Origin City']}:")
trajectory, displacement = shortest_path(df_distance_pruned, final_distance_order.loc[0, 'Origin City'])
print(" > ".join(trajectory))
print(f"Total covered distance: {displacement:.0f} km")

                Origin City  Covered Distance (km)
0                 Barcelona                   2646
1   Hospitalet de Llobregat                   2652
2                  Zaragoza                   2693
3                      Vigo                   2873
4                   Sevilla                   2956
5                   Córdoba                   2981
6                    Málaga                   3066
7                    Murcia                   3082
8                  Alicante                   3134
9                  Valencia                   3200
10               Valladolid                   3357
11                   Bilbao                   3431
12                    Gijón                   3439


The shortest route is to start from Barcelona:
Barcelona > Hospitalet de Llobregat > Zaragoza > Bilbao > Gijón > Valladolid > Vigo > Sevilla > Córdoba > Málaga > Murcia > Alicante > Valencia
Total covered distance: 2646 km